fip:
  default_station: 7
indicator:
  refresh_timeout: 120
spotify:
  use: true
  user_name: 
  user_token: 
  client_id: ffe193071be8425e98050c4a7b36ab31
  client_secret: 86064d1ce9d24c30940fdb42c67aa808
  redirect_uri: https://github.com/feeloow/fip-indicator
